### ISSUE TITLE
Possible to skip evaluation?

### ISSUE THREAD

**Issue by jtpavlock** [ngoldbaum/RunNotebook#10]
Hi there, thanks for this awesome extension to sphinx.

I was wondering if there was a way to prevent the evaluation of the jupyter notebooks when using the `::notebook` directive and instead just use their current contents.

The reason I am asking is because I have a lot of notebook files that make network calls and aren't always 100% reliable and it slows down the build process considerably. Thanks!

**Comment by ngoldbaum** [comment]
Please feel free to implement this. I doubt you’d need to know too much about sphinx.

**Comment by jtpavlock** [comment]
I'll see what I can do, thanks for the quick response
