### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: full

### ISSUE THREAD

**Issue by ax3l** [ngoldbaum/RunNotebook#12]
Hi Nathan,

after following the installation guide, I get an error on build of the form:
```
Exception occurred:
  File "/home/axel/sw/miniconda3/envs/sphinx/lib/python3.9/site-packages/jinja2/loaders.py", line 429, in load
    raise TemplateNotFound(name)
jinja2.exceptions.TemplateNotFound: full
```

I cannot find a solution to this, but suspect I need to install something more... Have you seen this before?

Jinja2 is at version 2.11.2 and I am at Python 3.9.0 (same issue with 3.8.0).

[sphinx-err-yncdfuip.log.txt](https://github.com/ngoldbaum/RunNotebook/files/5462245/sphinx-err-yncdfuip.log.txt)

**Comment by ngoldbaum** [comment]
Haven’t seen this, nope. Perhaps something changed in e.g. nbconvert?

**Comment by ngoldbaum** [comment]
Yeah I bet this is nbconvert 6.0 breaking things: https://nbconvert.readthedocs.io/en/latest/changelog.html

**Comment by ax3l** [comment]
Jup, I am on `nbconvert` version `6.0.1`.

**Comment by jzuhone** [comment]
@ngoldbaum any ideas on how to fix this?

**Comment by ngoldbaum** [comment]
Downgrade nbconvert or figure out how to adapt to the new APIs.
