### ISSUE TITLE
Cannot import name 'Directive' (class was deprecated)

### ISSUE THREAD

**Issue by addisonlynch** [ngoldbaum/RunNotebook#8]
Sphinx - 1.7.2

After adding the extension to Sphinx:

>Extension error:
  Could not import extension RunNotebook (exception: cannot import name 'Directive')

It seems the problem is coming from here:

https://github.com/ngoldbaum/RunNotebook/blob/40b9e49e30a406c07dda95f285a14eee6ef2b7d9/RunNotebook/notebook_sphinxext.py#L7

From the Sphinx [changelog](http://www.sphinx-doc.org/en/master/changes.html), it seems that ``sphinx.util.compat.Directive`` was deprecated as of the 1.7 release:

>1.6b1
> sphinx.util.compat.Directive class is now deprecated. Please use instead docutils.parsers.rst.Directive

I did try reverting to 1.6.1, but an encoding error was thrown: 

![image](https://user-images.githubusercontent.com/21162161/38465448-9fae909a-3ad0-11e8-8e1d-ec0932cff2a1.png)

Don't have as much time as I'd like to investigate and create a pull at the moment, but will try to take a look at some point. Thanks for writing this library!

**Comment by addisonlynch** [comment]
@ngoldbaum still seeing the unicode error...is this something wrong on my end? Have tried with a few different notebooks, including a trivial "hello world" notebook. Thanks

![image](https://user-images.githubusercontent.com/21162161/38469860-3a9a0d5c-3b10-11e8-84b5-7613b0bb5e1d.png)

**Comment by ngoldbaum** [comment]
I don’t see that issue, no. Please tell me more about your python environment, including versions of sphinx, jupyter, and nbconvert, as well as operating system. Do you see that error when building the example Sphinx project in the repo?
